---
- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present
- name:  Install Python Docker SDK
  ansible.builtin.pip:
    name: docker
- name: Give User Docker Access
  ansible.builtin.user:
    name: "{{ docker_user }}"
    append: true
    groups: ["docker"]